import distri_alert_if_Rubrik_TBD_Error_Message from '@salesforce/label/c.Distri_alert_if_Rubrik_TBD_Error_Message'
import distri_alert_if_Marketplace_Error_message from '@salesforce/label/c.Distri_alert_if_Marketplace_Error_message'
import disti_changes_from_Non_Aspen_to_Aspen_Error_message from '@salesforce/label/c.Disti_changes_from_Non_Aspen_to_Aspen_Error_message'
import unapproved_Countries_Notify from '@salesforce/label/c.Unapproved_Countries_Notify'
export default{
distri_alert_if_Rubrik_TBD_Error_Message:distri_alert_if_Rubrik_TBD_Error_Message, 
distri_alert_if_Marketplace_Error_message:distri_alert_if_Marketplace_Error_message,
disti_changes_from_Non_Aspen_to_Aspen_Error_message:disti_changes_from_Non_Aspen_to_Aspen_Error_message,
unapproved_Countries_Notify:unapproved_Countries_Notify
}