import { LightningElement, wire, api, track } from 'lwc';
import { ShowToastEvent } from 'lightning/platformShowToastEvent';
import { NavigationMixin } from 'lightning/navigation';
import { getRecord } from 'lightning/uiRecordApi';
import CaseSummaryByProjectGeniusText from '@salesforce/label/c.CaseSummaryByProjectGeniusText';
import getFeedbackRecord from '@salesforce/apex/CaseSummaryFeedbackController.getFeedbackRecord';
import saveFeedbackRecord from '@salesforce/apex/CaseSummaryFeedbackController.saveFeedbackRecord';
import getAutoGeneratedField from '@salesforce/apex/CaseSummaryFeedbackController.getAutoGeneratedField';

// const CASE_FIELDS = ['Case.AutoGenerated__c'];

const actions = [
    { label: 'Show details', name: 'show_details' }
];

export default class AutoGenerated_sectionOnCase extends NavigationMixin(LightningElement) {
    

    @api recordId;
    @track AutoGeneratedSectionHide = false;
    @track error = false;

    @track showLoader = false;
    @track showVoteUp = false;
    @track showVoteDown = false;
    @track showFeedbacks = false;
    @track showJsonObject = false;
    @track feedbackComment = '';
    @track problemType = '';
    @track problemSection = '';
    @track feedbackRecordId = '';
    @track voteUp = false;
    @track voteDown = false;
    @track lastUpdatedAt = '';
    @track jsonEntries = [];
    @track feedbackData = [];
    jsonObject = {};
    checkAllValid = true;
    activeSections = [];
    userTimeZoneId;
    localDateTime;
    CaseSummaryText = CaseSummaryByProjectGeniusText;

    
   
    feedbackColumns = [
        {
            type: 'action',
            typeAttributes: { rowActions: actions },
        },
        { label: 'Vote Up', fieldName: 'Vote_Up__c' },
        { label: 'Vote Down', fieldName: 'Vote_Down__c', type: 'text' },
        { label: 'Select A Section', fieldName: 'Problem_in_Section__c', type: 'text' },
        { label: 'Problem Type', fieldName: 'Problem_Type__c', type: 'text' },
        { label: 'Feedback Comment', fieldName: 'VoteUp_Feedback_comment__c', type: 'text' },
    ];


    @wire(getAutoGeneratedField, { caseId: '$recordId' })
    wiredCase({ error, data }) {
        if (data && data.autoGenerated) {
            try {
                this.jsonObject = JSON.parse(data.autoGenerated);
                this.AutoGeneratedSectionHide = false;
                this.showJsonObject = true;
                this.userTimeZoneId = data.userTimeZone;
                this.getJsonEntries();
            } catch (e) {
                this.error = true;
                console.error('Error parsing JSON:', e);
            }
        } else if (error) {
            this.error = true;
            console.error('Error fetching case record:', error);
        }
    }

    // connectedCallback() {
    //     //--- call method to fetch feedback data ----- 
    //     this.fetchFeedbackData();
    // }


    getJsonEntries() {
        const regex = /(\d{2}:\d{2}:\d{2})\s+UTC\s+([A-Za-z]+\s+\d{1,2},\s+\d{4})/;

        Object.entries(this.jsonObject || {}).forEach(([key, value]) => {
            let fldValue;
            let outputString;
            if (key.startsWith('__')) {
                return; // Skip keys starting with '__'
            }
            if (key.toLowerCase() == 'last_updated_at' || key.toLowerCase() === 'last_generated_at') {
                this.lastUpdatedAt = this.convertToUserTimeZone(value);
                return;
            }

            fldValue = typeof value === 'object' && value !== null ? JSON.stringify(value, null, 2) : this.formatValue(value);

            const match = fldValue.match(regex);
            if (match) {
                const utcDateTimeString = `${match[1]} UTC ${match[2]}`;
                const utcDate = new Date(utcDateTimeString); // JS parses this in UTC
                const localDateTime  = this.convertToUserTimeZone(utcDate);
                // Replace the original UTC part with converted string
                outputString = fldValue.replace(regex, localDateTime);
            }
            else{
                outputString = fldValue;
            }

            this.jsonEntries.push({
                key: this.formatKey(key),
                value: outputString
            });
        });

    }

    formatKey(key) {
        // Remove underscores and capitalize each word
        let keyName = key
            .split('_')
            .map(word => word.charAt(0).toUpperCase() + word.slice(1))
            .join(' ');
        this.activeSections.push(keyName);
        return keyName;
    }

    formatValue(value) {
        if (typeof value === 'string') {
            return value.replace(/\n/g, '<br>');
        }
        return value;
    }

    // ----- To get Arrow icon -----
    get iconName() {
        return this.AutoGeneratedSectionHide ? 'utility:chevrondown' : 'utility:chevronright';
    }

    toggleSection() {
        this.AutoGeneratedSectionHide = !this.AutoGeneratedSectionHide;
    }

    // --- show dialog for Vote up ----- 
    handleVoteUp(){
        this.showVoteUp = true;
        this.showVoteDown = false;
        this.showLoader = false;
        this.showFeedbacks = false;
        this.fetchFeedbackData();
    }

    handleVoteDown(){
        this.showVoteDown = true;
        this.showVoteUp = false;
        this.showLoader = false;
        this.showFeedbacks = false;
        this.fetchFeedbackData();
    }

    handleViewFeedback(){
        this.showFeedbacks = true;
        this.showVoteDown = false;
        this.showVoteUp = false;
        this.showLoader = false;
        this.fetchFeedbackData();
    }

    handleClose() {
        this.showVoteDown = false;
        this.showVoteUp = false;
        this.showLoader = false;
        this.showFeedbacks = false;
    }

    handleSave(e) {
        let voteType = e.target.dataset.voteType;
        if(voteType == 'voteUp'){
            this.voteUp = true;
            this.voteDown = false;
            const feedbackCommentField = this.template.querySelector("lightning-input-field[data-id='feedbackCommentUp']");
            const selectedSectionField = this.template.querySelector("lightning-input-field[data-id='feedbackSection']");
            this.feedbackComment = feedbackCommentField.value;
            this.problemType = '';
            this.problemSection = selectedSectionField.value;
            this.checkAllValid = true; 

            if (!selectedSectionField.value) {
                selectedSectionField.reportValidity(); 
                this.checkAllValid = false;
            }

            if (!feedbackCommentField.value) {
                feedbackCommentField.reportValidity(); 
                this.checkAllValid = false;
            }
        }
        else if(voteType == 'voteDown'){
            this.voteUp = false;
            this.voteDown = true;
            const problemTypeField = this.template.querySelector("lightning-input-field[data-id='problemType']");
            const problemSectionField = this.template.querySelector("lightning-input-field[data-id='problemSection']");
            const feedbackCommentDownField = this.template.querySelector("lightning-input-field[data-id='feedbackCommentDown']");
            this.problemType = problemTypeField.value;
            this.problemSection = problemSectionField.value;
            this.feedbackComment = feedbackCommentDownField.value;

            if (!problemSectionField.value) {
                problemSectionField.reportValidity(); 
                this.checkAllValid = false;
            }

            if (!feedbackCommentDownField.value) {
                feedbackCommentDownField.reportValidity(); 
                this.checkAllValid = false;
            }

            if (!problemTypeField.value) {
                problemTypeField.reportValidity();
                this.checkAllValid = false; 
            }

            if(problemSectionField.value && feedbackCommentDownField.value && problemTypeField.value){
                this.checkAllValid = true; 
            }
        }

        // Construct the record object to save
        const feedbackRecord = {
            sobjectType: 'Case_Summary_by_Project_Genius_Feedback__c',
            Case__c: this.recordId,
            Vote_Up__c: this.voteUp,
            Vote_Down__c: this.voteDown,
            VoteUp_Feedback_comment__c: this.feedbackComment,
            Problem_Type__c: this.problemType,
            Problem_in_Section__c: this.problemSection
        };

        /* Allow multiple feedbacks
        if(this.feedbackRecordId != ''){
            feedbackRecord.Id =  this.feedbackRecordId;
        }*/

        // Call saveFeedbackRecord Apex method to save the data
        if (this.checkAllValid) {
            this.showLoader = true;
            saveFeedbackRecord({ feedbackRecord })
                .then(() => {
                    this.showLoader = false;
                    this.showVoteDown = false;
                    this.showVoteUp = false;
                    // Show success toast message
                    this.dispatchEvent(
                        new ShowToastEvent({
                            title: 'Success',
                            message: 'Changes saved successfully',
                            variant: 'success'
                        })
                    );
                })
                .catch(error => {
                    console.log('error 12345 ', error);
                    this.showLoader = false;
                    // Show error toast message if record update fails
                    this.dispatchEvent(
                        new ShowToastEvent({
                            title: 'Error updating record',
                            message: error.body.message,
                            variant: 'error'
                        })
                    );
                });
        }
    }

    // Method to fetch the record data
    fetchFeedbackData() {
        getFeedbackRecord({ relatedCaseId: this.recordId })
            .then(result => {
                console.log('result ',result);
                this.feedbackData = [...result];
            })
            .catch(error => {
                console.error('Error fetching feedback record:', error);
            });
    }

    convertToUserTimeZone(utcString) {
        let utcDate = new Date(utcString);
        this.localDateTime = new Intl.DateTimeFormat('en-US', {
            timeZone: this.userTimeZoneId,
            year: 'numeric',
            month: '2-digit',
            day: '2-digit',
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit',
            hour12: false
        }).format(utcDate);

        return this.localDateTime;
    }

    //-------- open feedback record details on row action ----
    handleRowAction(event) {
        const recordId = event.detail.row.Id;
        const objectApiName = 'Case_Summary_by_Project_Genius_Feedback__c'; // Change as needed
        const url = `/lightning/r/${objectApiName}/${recordId}/view`;

        // Open in new tab
        window.open(url, '_blank');
    }
}