/********************************************************************************************************
* Name              : KnowledgeCategoryHomeTest
* Purpose           : KnowledgeCategoryHomeTest is Used for Testing KnowledgeCategoryHome Class
*********************************************************************************************************/
@isTest
public class KnowledgeCategoryHomeTest{
    
    public static testmethod void categoryhomeTest(){
        KnowledgeCategoryHome obj = new KnowledgeCategoryHome();
        obj.getDataCategoryGroupInfo();
        
    }
}