/**
* Class Name :- QuoteTermModel
* Author :- Mustakim Shaikh
* Created Date :- May 12th ,2025
* @description : SBQQ Quote Term Model
* TestClass   : QuoteTermModelTest
// ********************Mofification Log *****************************************************************************
*     
* Modified By          Date             Description (Include Jira Details)
* 
*    
* 
// ********************Modification Log *****************************************************************************
**/
public class QuoteTermModel {
    public String value;
    public String type;
    public Id standardTermId;
    public Id quoteId;
    public Boolean locked;
    public String label;
    public Id id;
}