"use strict"
import { LightningElement, track, api, wire } from 'lwc';
import updateDataCategory from '@salesforce/apex/SU_Knowbler.DataCategoryController.updateDataCategory';
import canPublishArticles from '@salesforce/apex/SU_Knowbler.KCSPublishController.canPublishArticles';
import getArticleNumber from '@salesforce/apex/SU_Knowbler.knowledgeSearchController.getArticleNumber';
import PublishArticle from '@salesforce/apex/SU_Knowbler.KCSPublishController.publishArticle';
import ScheduleArticle from '@salesforce/apex/SU_Knowbler.KCSPublishController.scheduleArticle';
import GetArticleFields from '@salesforce/apex/SU_Knowbler.KCSPublishController.getArticleFields';
import AttachArticleToCase from '@salesforce/apex/SU_Knowbler.KCSPublishController.attachArticleToCase';
import getRecordDetailsWithNumbers from "@salesforce/apex/SU_Knowbler.knowledgeSearchController.getRecordDetailsWithNumbers";
import getNamespace from '@salesforce/apex/SU_Knowbler.knowledgeSearchController.getNamespace';
import getCurrentCase from '@salesforce/apex/SU_Knowbler.knowledgeSearchController.getCurrentCase';
import isCaseClosed from '@salesforce/apex/SU_Knowbler.KCSPublishController.isCaseClosed';
import getComments from '@salesforce/apex/SU_Knowbler.knowledgeSearchController.getAllComments';
import { getRecord, createRecord, updateRecord } from 'lightning/uiRecordApi';
import UserId from '@salesforce/user/Id';
import { getObjectInfo,getPicklistValues } from 'lightning/uiObjectInfoApi';
import { ShowToastEvent } from 'lightning/platformShowToastEvent';
//import INDUSTRY_FIELD from '@salesforce/schema/KnowledgeArticleVersion.Language';
import knowblerPubsub from 'c/knowblerPubsub';
import { CurrentPageReference } from 'lightning/navigation';
import getBackendUrl from '@salesforce/apex/SU_Knowbler.knowledgeSearchController.getBackendUrl';
import getRecordRelatedFiles from '@salesforce/apex/SU_Knowbler.FileUploaderClass.getRelatedFilesByRecordId';
import attachRecordIdToFiles from '@salesforce/apex/SU_Knowbler.FileUploaderClass.attachRecordIdToFiles';
import deleteUploadedFile from '@salesforce/apex/SU_Knowbler.FileUploaderClass.deleteFile';

export default class KnowblerArticleCreation extends LightningElement {
  @track publishmethod;
  @track userId = UserId;
  @api flagview;
  @track publishrecords;
  @api draftarticlemode;
  @api recordId;
  @api flagedit;
  @track activevalue = "0";
  @api recordtype;
  @api currentid;
  @api casedata;
  @api casenumber;
  @api jwttoken;
  @api contentHealthSettings;
  @api removeFeedContentList;
  @api endpoint;
  @api uniqueNumber;
  @api language;
  @api autoGeneratedTitle;
  @api autoGeneratedSummary;
  @api clientSettings;
  @api mappingfields;
  @api norecordflag;
  @track boolSave = false;
  @track stayleaveflag = false;
  @track createflag = false;
  @api newnumber;
  @track progressflag = false;
  @track mapping = [];
  @api kcsheight;
  @api flexipageregionwidth;
  @api kcssupport;
  @track myRecordId = "";
  @track recordtypeID = "";
  @track uploadedFiles = [];
  @track allFilesList = [];
  @track hasFileUploadPermission = true;
  @track loadFilesList = false;
  @track uploadedName = '';
  @track sectionData = [];
  @api iseditarticle;
  @track fileField = "";
  @track typeFile = "";
  @track fileName = "";
  @track uploadCheck = false;
  @api loadingcard;
  @track showloader = true;
  refreshdata;
  @track objInfo;
  isValueChange = false;
  @track isPublish = false;
  valid = true;
  @track fromBack = false;
  @track firstTime = false;
  @api alldatacategories;
  @api destobj;
  @track type = "success";
  @api successMsg = "Video Embedded";
  @track messageIsHtml = false;
  @track showToastBar = false;
  @api autoCloseTime = 2000;
  @api videoLink;
  @api getIconName;
  @api selectedOption;
  @api myVal = "";
  @track mapp = [];
  @track canpublisharticles;
  @track permissiontopublish;
  @api caseid;
  @api displayTitleLoader;
  @api displaySummaryLoader;
  @api generateSummaryFields;
  @track articleId;
  @track articlenumber;
  @track ispublishnow = false;
  @track isschedulepublish = false;
  @track scheduledate;
  @track ispublishattach;
  @track showEvaluateLoader = false;
  @track contentHealthData;
  @track calculateContentHealthApiPayload;
  @track isresolution;
  @track isreference;

  @track updatingrecords;
  @track fieldset = {};
  @track namespace;

  @api llmStatus;

  @track duplicacylisting = true;
  @track recordt;
  @track articleListData = {
    showEditPage: false,
    showDetailPage: false,
    showEditDetailPage: false,
    showConfiguration: false,
    searchText: '',
    showArticlesScreen: true,
    detailArticle: {},
    currentId: '',
    configRecord: [],
    mappingFields: [],
    query: {
      numPerPage: 10,
      offset: 0,
      currentPage: 1,
      tabcontent: 0,
      count: 0,
      fromTab: false
    },
    isedit: false,
    userLanguage: '',
    hitIndex: 2,
    flagForm: '',
    createArtcleMapping: {}
  };

  stayLeave;
  articleSuccessful;
  saveProgress;
  file;
  dependPicklist;
  controlPicklist;
  save;
  close;
  generated;
  caseclosed;

  tooltipContent = '';
  checkEmptyValidator = false;
  checkDataCatLoad = false;
  contentHealthCheckArray=[];

  @track exp;
  @track tabs;
  @track query = {
    tabcontent: 0,
    articleCretae: 1
  };
  @track dataCategories = [];
  @track selectedCategoryTree = [];
  @track dataCategoriesBck = [];
  @track showSection = true;
  @track createArticleMapping = {};
  @track titleGenerated = false;
  @track displayDuplicacyModal = false;
  @track articlesData = [];
  @track proceedAnywayAction = "save-as-draft";
  @track submitForReview = false;
  @track saveAsDraftEvent = null;
  @track cardLength = 0;
  @api author;
  baseUrl = '';
  knowblerModalComponent = 'c-knowbler-modal-component'

  get acceptedFormats() {
    return [".jpg", ".png", ".jpeg", ".gif", ".txt", ".doc", ".docx", ".xlsx"];
  }

  @api
  set createartclemapping(data) {
    if (data) {
      this.createArticleMapping = JSON.parse(JSON.stringify(data));
      if (this.flexipageregionwidth) {
        this.setArticleData();
        if (this.createArticleMapping?.query) {
          this.query = {};
          this.query = { ...this.createArticleMapping?.query };
          this.activevalue = this.createArticleMapping?.query?.tabcontent;
        }
      }
      if (
        this.createArticleMapping &&
        this.createArticleMapping.selectedCategoryTree &&
        this.createArticleMapping.selectedCategoryTree.length
      ) {
        this.selectedCategoryTree =
          this.createArticleMapping.selectedCategoryTree;
      }
      if (
        this.createArticleMapping &&
        this.createArticleMapping.dataCategories &&
        this.createArticleMapping.dataCategories.length
      ) {
        this.dataCategories = this.createArticleMapping.dataCategories;
      }
    }
  }
  get createartclemapping() {
    return this.createArticleMapping;
  }

  get getDisplayAutoGenLoader() {
    return this.displaySummaryLoader || this.displayTitleLoader;
  }

  get getLlmStatus() {
    return !(this.llmStatus && this.llmStatus.type && this.llmStatus.type === 0);
  }

  get getRegenerationIconClass() {
    return this.displaySummaryLoader || this.displayTitleLoader
      ? 'knowbler__regenerate-icon knowbler__disable-regenerate-icon'
      : 'knowbler__regenerate-icon';
  }

  @wire(canPublishArticles)
  canpublisharticles({ error, data }) {
    if (data) {
      this.canpublisharticles = data;
    } else if (error) {
      this.error = error;
      this.template.querySelector('c-knowbler-modal-component').showError(this.error);
    }
  }

  @wire(getObjectInfo, { objectApiName: "$destobj" })
  objectInfo({ error, data }) {
    if (data) {
      this.objInfo = data;
      if (this.objInfo?.recordTypeInfos) {
        var b = this.objInfo?.recordTypeInfos;
        var a = Object.keys(b).map((key) => ({ key: key, ...b[key] }));
        if (
          this.recordtype != undefined ||
          this.recordtype != null ||
          this.recordtype != ""
        ) {
          var c = a.find((ele) => ele.name.toLowerCase() == this.recordtype.toLowerCase());
          this.recordtypeID =
            this.recordtype == "Master" ? "" : c?.recordTypeId;
        } else {
          this.recordtypeID = "";
        }
      }
      this.getConnectedData();
    } else if (error) {
      this.error = error;
      if(this.template.querySelector('c-knowbler-modal-component'))
      this.template.querySelector('c-knowbler-modal-component').showError(error);
    }
  }

  @wire(getRecord, { recordId: "$currentid", fields: "$mappingfields" })
  getDetails({ error, data }) {
    if (data) {
      if (this.iseditarticle && data) {
        if (this.createArticleMapping?.mapping) {
          this.setArticleData();
        } else {
          let newData = Object.assign({}, data);
          if (this.firstTime == false) {
            this.getIntialData(newData);
          } else {
            this.setMapping(newData);
          }
        }
        if (this.createArticleMapping?.query && data) {
            this.query = {}
            this.query = { ...this.createArticleMapping?.query };
            this.activevalue = this.createArticleMapping?.query?.tabcontent;
      }


      }
    } else if (error) {
      this.error = error;
      this.template.querySelector(this.knowblerModalComponent).showError(error);
    }
  }

  async getCase() {
    try {
      const caseId = this.casedata?.Id;
      const response = await getCurrentCase({ recordId: caseId });
      if (response.length) {
        this.casedata = { ...response[0] };
      }
    } catch (error) {
      this.template
        .querySelector(this.knowblerModalComponent)
        .showError(error);
    }
  }

  renderedCallback() {
    if (this.flexipageregionwidth) {
      let heightcreation = Math.floor(this.kcsheight - 50);
      if (this.template.querySelector(".layout-body-two"))
        this.template.querySelector(
          ".layout-body-two"
        ).style = `height:${heightcreation}px`;
    } else {
      let heightcreation = Math.floor(screen.height - 220) + "px";
      if (this.template.querySelector(".layout-body-two"))
        this.template.querySelector(
          ".layout-body-two"
        ).style = `height:${heightcreation}`;
    }
    this.populateContentHealthCheck();
    this.checkEmptyValidator = this.handleChangeCheck();
  }

  createCustomUrl(articleObj) {
    const testRegex = /{{.*?}}/g;
    const str = this.clientSettings.base_href;
    let baseHref = this.clientSettings.base_href;
    let baseHrefTemp;

    if (baseHref.includes("{{Title}}")) {
      baseHref = baseHref.replace(
        "{{Title}}",
        articleObj.Title.split(" ")
          .join("-")
          .replace(/[&\/\\#, +()$~%.'":*?<>{}]/g, "-")
          .replace(/-{2,}/g, "-")
      );
    }

    while ((baseHrefTemp = testRegex.exec(str)) !== null) {
      if (baseHrefTemp.index === testRegex.lastIndex) {
        testRegex.lastIndex += 1;
      }
      baseHrefTemp.forEach((match) => {
        baseHref = baseHref.replace(
          match,
          articleObj[match.replace("{{", "").replace("}}", "")]
        );
      });
    }

    return baseHref;
  }

  handleLoad(event) {
    event.detail.layout.sections.forEach((ele) => {
      ele.layoutRows.forEach((el) => {
        if (
          el.layoutItems[0].layoutComponents[0] &&
          el.layoutItems[0].layoutComponents[0].apiName !== null &&
          el.layoutItems[0].layoutComponents[0].componentType !== "EmptySpace"
        ) {
          this.mapp.push(el.layoutItems[0].layoutComponents[0].apiName);
        }
      });
    });
    let mappingfiel = [];
    this.mapp.forEach((el) => {
      mappingfiel.push(this.destobj + "." + el);
    });
    this.mappingfields = [...[]];
    this.mappingfields = [...mappingfiel];
    this.firstTime = true;
  }

  getConnectedData() {
    if (!this.iseditarticle) {
      if (this.createArticleMapping?.mapping) {
        this.setArticleData();
      } else {
        this.getIntialData();
      }
    }
    // await this.sleep(3000);
    this.showloader = false;
    if (this.createArticleMapping?.query) {
      this.query = {};
      this.query = { ...this.createArticleMapping?.query };
      this.activevalue = this.createArticleMapping?.query?.tabcontent;
    }
  }

  get contentHealthCheckClass(){
    if ((this.contentHealthSettings && this.contentHealthSettings.previewArticleContentHealth) && this.checkEmptyValidator) {
      this.tooltipContent = 'Preview Content Health'
    } else {
      this.tooltipContent = 'Required fields to generate content health are empty'
    }
    return ((this.contentHealthSettings && this.contentHealthSettings.previewArticleContentHealth && this.contentHealthSettings.activated) && this.checkEmptyValidator && this.checkDataCatLoad) ? 'knowbler__calculate-health-btn' : 'knowbler__calculate-health-btn knowbler__calculate-health-btn-disable';
  }
  setArticleData() {
    this.showSection = this.createArticleMapping?.showSection;
    if (this.createArticleMapping?.tabs) {
      this.tabs = [...[]];
      this.tabs = [...this.createArticleMapping?.tabs];
    }
    this.uploadCheck = this.createArticleMapping?.uploadCheck;
    this.uploadedName = this.createArticleMapping?.uploadedName;
    this.mapping = [...[]];
    this.isValueChange = this.createArticleMapping?.isValueChange;

    this.mapping = [...this.createArticleMapping?.mapping];
    this.handleChange('setValue');
    if(this.createArticleMapping?.dataCategories && typeof(this.createArticleMapping?.dataCategories)=='object')
     this.dataCategoriesBck=(this.createArticleMapping?.dataCategories);
     else
     this.dataCategoriesBck=JSON.parse(this.createArticleMapping?.dataCategories);

  }
  @wire(CurrentPageReference) objpageReference;
   @wire(getNamespace)
    getnsp({ error, data }) {
        if (data) {
            this.namespace = data;
            this.error = null;
        } else if (error) {
            this.error = error;
            this.namespace = null;
        }
    }


  connectedCallback()
  {
    this.baseUrl = window.location.origin;
    if (this.iseditarticle && this.currentid) {
      this.infoUploadedFiles();
    }
    this.exp = this.kcssupport[0].salesforceExperience;
    this.publishrecords = false;
    if(this.clientSettings && this.clientSettings.attach_to_close_cases === true) {
      this.checkCaseClosed();
    }
  }

  async infoUploadedFiles() {
    try {
      this.loadFilesList = true;
      const fileExtensionTypeMap = {
        'png': 'doctype:image',
        'jpg': 'doctype:image',
        'jpeg': 'doctype:image',
        'gif': 'doctype:image',
        'bmp': 'doctype:image',
        'tiff': 'doctype:image',
        'svg': 'doctype:image',
        'pdf': 'doctype:pdf',
        'doc': 'doctype:word',
        'docx': 'doctype:word',
        'dot': 'doctype:word',
        'dotx': 'doctype:word',
        'xls': 'doctype:excel',
        'xlsx': 'doctype:excel',
        'xlt': 'doctype:excel',
        'xltx': 'doctype:excel',
        'ppt': 'doctype:ppt',
        'pptx': 'doctype:ppt',
        'pot': 'doctype:ppt',
        'potx': 'doctype:ppt',
        'pps': 'doctype:ppt',
        'ppsx': 'doctype:ppt',
        'txt': 'doctype:txt',
        'rtf': 'doctype:txt',
        'csv': 'doctype:csv',
        'html': 'doctype:html',
        'htm': 'doctype:html',
        'xml': 'doctype:xml',
        'zip': 'doctype:zip',
        'rar': 'doctype:zip',
        '7z': 'doctype:zip',
        'tar': 'doctype:zip',
        'gz': 'doctype:zip',
        'mp3': 'doctype:audio',
        'wav': 'doctype:audio',
        'aac': 'doctype:audio',
        'flac': 'doctype:audio',
        'ogg': 'doctype:audio',
        'mp4': 'doctype:video',
        'mov': 'doctype:video',
        'wmv': 'doctype:video',
        'avi': 'doctype:video',
        'mkv': 'doctype:video',
        'flv': 'doctype:video',
        'default': 'doctype:unknown'
      };
      const fileInfos = await getRecordRelatedFiles({ recordId: this.currentid });
      this.hasFileUploadPermission = true;
      const files = fileInfos.map(file => {
        return {
            ...file,
            fileIcon: fileExtensionTypeMap[file?.fileType.toLowerCase()] || fileExtensionTypeMap['default'],
            fileLink: `${this.baseUrl}/${file.documentId}`,
            disable : false
        };
      });
      this.allFilesList = files;
      this.loadFilesList = false;
    } catch (error) {
      this.hasFileUploadPermission = false;
      console.error('Error checking permission:', error);
    }
  }

  getFileIcon(fileType) {
    const fileTypeMap = {
      'image/png': 'doctype:image',
      'image/jpeg': 'doctype:image',
      'image/jpg': 'doctype:image',
      'image/gif': 'doctype:image',
      'image/bmp': 'doctype:image',
      'image/tiff': 'doctype:image',
      'image/svg+xml': 'doctype:image',
      'application/pdf': 'doctype:pdf',
      'application/msword': 'doctype:word',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'doctype:word',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.template': 'doctype:word',
      'application/vnd.ms-excel': 'doctype:excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': 'doctype:excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.template': 'doctype:excel',
      'application/vnd.ms-powerpoint': 'doctype:ppt',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation': 'doctype:ppt',
      'application/vnd.openxmlformats-officedocument.presentationml.template': 'doctype:ppt',
      'application/vnd.openxmlformats-officedocument.presentationml.slideshow': 'doctype:ppt',
      'text/plain': 'doctype:txt',
      'application/rtf': 'doctype:txt',
      'text/csv': 'doctype:csv',
      'text/html': 'doctype:html',
      'application/xml': 'doctype:xml',
      'application/zip': 'doctype:zip',
      'application/x-rar-compressed': 'doctype:zip',
      'application/x-7z-compressed': 'doctype:zip',
      'application/x-tar': 'doctype:zip',
      'application/gzip': 'doctype:zip',
      'audio/mpeg': 'doctype:audio',
      'audio/wav': 'doctype:audio',
      'audio/aac': 'doctype:audio',
      'audio/flac': 'doctype:audio',
      'audio/ogg': 'doctype:audio',
      'video/mp4': 'doctype:video',
      'video/quicktime': 'doctype:video',
      'video/x-ms-wmv': 'doctype:video',
      'video/x-msvideo': 'doctype:video',
      'video/x-matroska': 'doctype:video',
      'video/x-flv': 'doctype:video',
      'default': 'doctype:unknown'
    };

    return fileTypeMap[fileType] || 'doctype:attachment';
  }

  handleUploadFinished(event) {
    const files = event.detail.files;
    const uploadedFile = files.map(val => {
      const icon = this.getFileIcon(val.mimeType);
      val.fileIcon = icon;
      val.fileLink = `${this.baseUrl}/${val.documentId}`;
      val.disable = false;
      return val;
    });
    this.uploadedFiles = [...this.uploadedFiles, ...uploadedFile ];
    this.allFilesList = [...this.allFilesList, ...uploadedFile];
  }

  async deleteFile(id) {
    const documentId = id;
    try {
      await deleteUploadedFile({ documentId });
      this.uploadedFiles = this.uploadedFiles.filter(file => file.documentId !== documentId);
      this.allFilesList = this.allFilesList.filter(file => file.documentId !== documentId);
    } catch (error) {
      console.log('Error deleting file: ' + error.body.message);
      this.template.querySelector(this.knowblerModalComponent).showError(error);
    }
  }

  handleRemoveUploadFile(e) {
    const documentId = e.currentTarget.dataset.id;
    const index = this.allFilesList.findIndex(file => file.documentId === documentId);
    this.allFilesList[index].disable = true;
    this.deleteFile(documentId);
  }

  async handleUploadFile(articleId) {
    try {
      const documentIds = this.uploadedFiles.map(file => file.documentId);
      await attachRecordIdToFiles({ documentIds: documentIds, recordId: articleId });
    } catch (error) {
        console.log('Error attaching Record ID to files: ' , error.body.message);
        this.template.querySelector(this.knowblerModalComponent).showError(error);
    }
  }

  checkCaseClosed() {
    isCaseClosed({ caseid: this.casedata && this.casedata.Id })
      .then((result) => {
        this.caseclosed = result;
      })
      .catch((error) => {
        this.error = error;
      });
  }
  @wire(getBackendUrl)
  wiredData({ error, data }) {
    if (data) {
      this.stayLeave =
        data +
        "/kcs-agent/kcs_custom_agent/resources/Assets/lwc-images/u_stayleave.svg";
      this.articleSuccessful =
        data +
        "/kcs-agent/kcs_custom_agent/resources/Assets/lwc-images/u_articlesuccessful.svg";
      this.saveProgress =
        data +
        "/kcs-agent/kcs_custom_agent/resources/Assets/lwc-images/u_saveprogress.svg";
      this.file =
        data +
        "/kcs-agent/kcs_custom_agent/resources/Assets/lwc-images/File.svg";
      this.dependPicklist =
        data +
        "/kcs-agent/kcs_custom_agent/resources/Assets/lwc-images/left_arrow.svg";
      this.controlPicklist =
        data +
        "/kcs-agent/kcs_custom_agent/resources/Assets/lwc-images/right_arrow.svg";
      this.save =
        data +
        "/kcs-agent/kcs_custom_agent/resources/Assets/lwc-images/save.svg";
      this.close =
        data +
        "/kcs-agent/kcs_custom_agent/resources/Assets/lwc-images/close.svg";
      this.generated =
        data +
        "/kcs-agent/kcs_custom_agent/resources/Assets/lwc-images/generated-successfully.svg";
    } else if (error) {
      console.error("Error:", error);
    }
  }

  disconnectedCallback() {
    if (!this.flexipageregionwidth) {
      if (this.template.querySelector("c-knowbler-data-category"))
        this.template.querySelector("c-knowbler-data-category").editForm();
      this.hanldesectionchange("change");
      this.dispatchEvent(
        new CustomEvent("fromcreatearticle", {
          detail: {
            flag: 1,
            isValueChange: this.isValueChange,
            currentid: this.currentid,
            mapping: this.mapping,
            query: this.query,
            showSection: this.showSection,
            tabs: this.tabs,
            uploadCheck: this.uploadCheck,
            uploadedName: this.uploadedName,
            dataCategories: this.dataCategories,
            selectedCategoryTree: this.selectedCategoryTree
          }
        })
      );
    }
    //unregisterAllListeners(this);
  }
  callEvent(data)
  {

  }
  handleclose(data)
  {
    this.handleLeave();
  }

  getPickListValues(res) {
    if (typeof res.valueArray == "object") {
      if (res.type === "picklist" && res.fromLogic) {
        return res.valueArray.value;
      }
      if (res.valueArray.length == 1) {
        return res.valueArray[0].value;
      } else if(res.valueArray.length>1){
        return  res.valueArray.join(';');
      }
        return '';

    } else if (typeof(res.valueArray) == 'string' && res?.fromLogic.includes('caseObject')) {
        return this.casedata[res?.fromLogic?.split('.')[1]] ? this.casedata[res?.fromLogic?.split('.')[1]] : '';
    }
    return res.fromLogic;
  }

  setMapping(newData) {
    this.myRecordID = this.currentid;
    //this.mapping=[...[]];
    this.mapp.forEach((ele) => {
      var otype = this.objInfo?.fields[ele].dataType;
      var olabel =this.objInfo?.fields[ele].label;
      var oval = newData.fields[ele].value;
      var cn = this.objInfo?.fields[ele].controllerName;
      var cf = this.objInfo?.fields[ele].controllingFields;
      var control = false;
      var depend = false;
      var isControllerLabel;


      if ((otype == "Picklist" || otype == "MultiPicklist") && cn == null) {
        depend = false;
        this.mapp.map((el) => {
          if (this.objInfo?.fields[el].controllerName == ele) {
            control = true;
          }
        });
      } else if (
        otype == "Picklist" ||
        (otype == "MultiPicklist" && cn != null)
      ) {
        depend = true;
        let controllingLabel = this.mapp.filter((el) => {
          if (this.objInfo?.fields[ele].controllerName == el) {
            return el;
          }
        });
        isControllerLabel = controllingLabel?.length
          ? this.objInfo?.fields[controllingLabel[0]].label
          : "";
      }

      if (otype != "file") {
        var isInlineHelp =
          !this.objInfo?.fields[ele]["inlineHelpText"] ||
          (this.objInfo?.fields[ele]["inlineHelpText"] &&
            this.objInfo?.fields[ele]["inlineHelpText"] == null)
            ? false
            : true;
        if (isInlineHelp)
          var InlineHelp = this.objInfo?.fields[ele]["inlineHelpText"];
      }
      if (otype == "Picklist" || otype == "MultiPicklist") {
        var obj = {
          name: ele,
          label: olabel,
          type: otype,
          value: oval,
          isAccess: true,
          InlineHelpText: InlineHelp,
          isInlineHelpText: isInlineHelp,
          isControllingPicklist: control,
          dependentPicklist: depend
        };
        if (depend) obj["isControllerLabel"] = isControllerLabel;
      } else {
        var obj = {
          name: ele,
          label: olabel,
          type: otype,
          value: oval,
          isAccess: true,
          InlineHelpText: InlineHelp,
          isInlineHelpText: isInlineHelp
        };
      }
      this.mapping.push(obj);
    });

    if (this.iseditarticle) {
      this.mapping.map((ele) => {
        if (ele.name.indexOf("__Name__s") > -1) {
          var elem = this.objInfo?.fields[ele.name].compoundFieldName;
          ele.name = elem;
          ele.type = "file";
          ele.label = elem.indexOf("__c") ? elem.slice(0, -3) : elem;
          ele.value = newData.fields[ele.label + "__Name__s"].value;
        }
        if (
          ele.name.indexOf("__ContentType__s") > -1 ||
          ele.name.indexOf("__Body__s") > -1 ||
          ele.name.indexOf("__Length__s") > -1
        ) {
          this.mapping = this.mapping.filter((el) => el !== ele);
        }

        if (ele.type == "file") {
          this.uploadedName =
            newData.fields[ele.name.replace("__c", "") + "__Name__s"].value;

          if (this.uploadedName != null) {
            this.uploadCheck = true;
          } else {
            this.uploadCheck = false;
          }
        } else {
          ele.value = newData.fields[ele.name].value;
        }
        return ele;
      });
    }

    this.mapping.map((ele) => {
      if (
        ele.type == "String" ||
        ele.type == "Boolean" ||
        ele.type == "Date" ||
        ele.type == "DateTime" ||
        ele.type == "Percent" ||
        ele.type == "Url" ||
        ele.type == "Phone" ||
        ele.type == "Currency" ||
        ele.type == "Reference" ||
        ele.type == "Email" ||
        ele.type == "Double"
      )
        ele["isString"] = true;
      else if (ele.type == "TextArea") {
        var x = this.objInfo?.fields[ele.name]["extraTypeInfo"];
        ele["is" + x] = true;
      } else if (ele.type == "MultiPicklist") {
        ele["isMultipicklist"] = true;
      } else
        ele["is" + ele.type.charAt(0).toUpperCase() + ele.type.slice(1)] = true;
    });

    this.showSection = true;
    this.norecordflag = false;
  }
  @api
  checkEditForm() {
    this.hanldesectionchange("change");
    this.dispatchEvent(
      new CustomEvent("fromcreatearticle", {
        detail: {
          isValueChange: this.isValueChange,
          currentid: this.currentid,
          mapping: this.mapping,
          query: this.query,
          showSection: this.showSection,
          tabs: this.tabs,
          uploadCheck: this.uploadCheck,
          uploadedName: this.uploadedName,
          dataCategories: this.dataCategories,
          selectedCategoryTree: this.selectedCategoryTree
        }
      })
    );
  }
  populateContentHealthCheck(){
    let res = JSON.parse(JSON.stringify(this.kcssupport));
    let config = res.filter(val=>val.RecordType === this.recordtype);
    if(config[0]?.autoGenConfig){
      config = config[0]?.autoGenConfig?.config;
    } else {
      config = false;
    }
    if(config)
    {
      for(let i=0;i<config.length;i++){
        if(config[i].checkHealth){
          if(!this.contentHealthCheckArray.includes(config[i].field)){
            this.contentHealthCheckArray.push(config[i].field);
          }
        }
      }
    }

    if(this.mapping && this.mapping.length>0){
      for(let i=0;i<this.mapping.length;i++){
        if(this.mapping[i].checkHealth){
          if(!this.contentHealthCheckArray.includes(this.mapping[i].name)){
            this.contentHealthCheckArray.push(this.mapping[i].name);
          }
        }
      }
    }

    if(config){
      for(let i=0;i<config.length;i++){
        if(this.contentHealthCheckArray.includes(config[i]?.field) && !config[i]?.checkHealth){
          this.contentHealthCheckArray = this.contentHealthCheckArray.filter((ele)=>ele !== config[i]?.field)
        }
      }
    }
  }
  getIntialData(newData) {

    this.myRecordId = this.currentid;
    let config = JSON.parse(JSON.stringify(this.kcssupport));

    config.forEach(element => {
      if (element.RecordType === this.recordtype){
        var access = element.mapping.every(res => res.sectionNumber == 1);
        var create = element.mapping.every(res => res.sectionNumber == 2);
        if(access){this.sectionchange(0)};
        if(create){this.sectionchange(1)};
        this.showSection = access || create ? true : false ;
        element.sectionList.map((res, index) => {
          res.label = res.name;
          res.value = index;

          element.mapping.map((elm) => {
            elm["is" + (elm.sectionNumber == 1 ? "Access" : "Create")] = true;
          });
          return res;
        });
        element.mapping.map((res) => {
          if (!this.iseditarticle && this.casedata) {
            if (
              typeof res?.fromLogic == "string" &&
              res?.fromLogic?.length > 0 &&
              res.name != "Language"
            ) {
              if (this.displayTitleLoader && res?.autoGen === true) {
                res.value = "";
              } else if (res?.fromLogic.split(" + ").length > 1) {
                res.value = "";
                const fieldLength = this.objInfo?.fields[res.name]?.length;
                let arr = res?.fromLogic.split(" + ");
                arr.forEach((nn) => {
                  if (nn.includes("caseObject")) {
                    res.value =
                      res.value +
                      (this.casedata[nn?.split(".")[1]]
                        ? this.casedata[nn?.split(".")[1]]
                        : "");
                  } else {
                    res.value = res.value + nn;
                  }
                });
                if (fieldLength && fieldLength < res.value.length) {
                  res.value = res.value.slice(0, fieldLength);
                }
              } else {
                if (
                  typeof this.casedata[res?.fromLogic.split(".")[1]] !=
                  "undefined"
                ) {
                  const fieldLength = this.objInfo?.fields[res.name]?.length;
                  res.value = this.casedata[res?.fromLogic.split(".")[1]];
                  if (fieldLength && fieldLength < res.value.length) {
                    res.value = res.value.slice(0, fieldLength);
                  }
                } else {
                  res.value = this.getPickListValues(res);
                }
              }
            } else if (typeof res?.fromLogic == "boolean") {
              res.value = res?.fromLogic;
            }
          }
          if (res.name == "Language") {
            if (res?.fromLogic == "") {
              res.value = "None";
            } else {
              if (res?.valueArray && res?.valueArray.value)
                res.value = res?.valueArray.value;
            }
          }

          if (res.type != 'file') {
            if(this.objInfo?.fields[`${res.name}`]!=undefined || this.objInfo?.fields[`${res.name}`]!=null)
              res.isInlineHelpText = (!this.objInfo?.fields[`${res.name}`]["inlineHelpText"] || (this.objInfo?.fields[`${res.name}`]["inlineHelpText"] && this.objInfo?.fields[`${res.name}`]["inlineHelpText"] == null)) ? false : true;
            if (res.isInlineHelpText)
              res.InlineHelpText =
                this.objInfo?.fields[`${res.name}`]["inlineHelpText"];
          }
          if (
            res.type == "string" ||
            res.type == "boolean" ||
            res.type == "date" ||
            res.type == "datetime" ||
            res.type == "percent" ||
            res.type == "url" ||
            res.type == "phone" ||
            res.type == "currency" ||
            res.type == "reference" ||
            res.type == "email" ||
            res.type == "double"
          )
            res["isString"] = true;
          else if (res.type == "textarea") {
            if (
              this.objInfo?.fields[`${res.name}`] != undefined &&
              this.objInfo?.fields[`${res.name}`] != null
            ) {
              var x = this.objInfo?.fields[`${res.name}`]["extraTypeInfo"];
              res["is" + x] = true;
            }
          } else
            res[
              "is" + res.type.charAt(0).toUpperCase() + res.type.slice(1)
            ] = true;
          if (!res.value) res.value = res.type == "boolean" ? false : "";
          if (
            res.type == "picklist" &&
            !res.dependentPicklist &&
            res.controllerName == null
          ) {
            res["isControllingPicklist"] = element.mapping.some(
              (el) => el.controllerName == res.name
            );
          }
          if (res.dependentPicklist) {
            let controllingLabel = element.mapping.filter(
              (el) => res.controllerName == el.name
            );
            res["isControllerLabel"] = controllingLabel?.length
              ? controllingLabel[0].label
              : "";
          }
          return res;
        });
        this.tabs = [...element.sectionList];
        element.sectionList.forEach((res) => {
          let sectionData = element.mapping.filter(
            (elm) => elm.sectionLabel == res.name
          );
          this.sectionData.push(
            sectionData && sectionData.length ? sectionData : []
          );
        });

        if (this.iseditarticle) {
          element.mapping.map((ele) => {
            if (ele.type == "file") {
              this.uploadedName =
                newData.fields[ele.name.replace("__c", "") + "__Name__s"].value;

              if (this.uploadedName != null) {
                this.uploadCheck = true;
              } else {
                this.uploadCheck = false;
              }
            } else {
              ele.value = newData.fields[ele.name].value;
            }
            return ele;
          });
        }

        this.mapping = [...element.mapping];

        if (this.iseditarticle) {
          for (var key in this.mapping) {
            if (this.mapping.hasOwnProperty(key)) {
              if (this.mapping[key].type == "file") {
                this.fieldset[
                  this.mapping[key].name.replace("__c", "") + "__Name__s"
                ] = this.uploadedName;
                delete this.fieldset[this.mapping[key]];
              } else {
                this.fieldset[this.mapping[key].name] = this.mapping[key].value;
              }
            }
          }
        }

        if (!this.iseditarticle) this.handleChange("Title");
      }
    });
    this.firstTime = true;
    this.handleChange('setValue');
    this.populateContentHealthCheck();
    this.checkEmptyValidator = this.handleChangeCheck();
  }

  handleChanges(event) {
    this.changeValue(event?.detail?.value, event?.detail?.fieldname);
  }

  handleVideo(event) {
    this.changeValue(event.detail);
    this.template.querySelector(this.knowblerModalComponent).showSuccess({ type: 'video', message: 'Video Embedded' });
  }

  get isCreateTab() {
    return this.query.tabcontent == 0 ? false : true;
  }
  saveClicked(event) {
    if (event.detail.dataCategory && event.detail.selectedCategoryTree) {
      this.isValueChange = true;
      this.dataCategories = JSON.stringify(event.detail.dataCategory);
      this.selectedCategoryTree = JSON.stringify(
        event.detail.selectedCategoryTree
      );
    }
    this.checkDataCatLoad = true;
  }

  hanldesectionchange(event) {
    const inputFields = this.template.querySelectorAll("lightning-input-field");
    if (inputFields) {
      inputFields.forEach((field) => {
        for (var i = 0; i < this.mapping.length; i++) {
          if (field.name == this.mapping[i].name) {
            this.mapping[i].value = field.value;
          }
        }
      });
    }
    if (event.detail?.tabcontent)
      this.query.tabcontent = event.detail?.tabcontent;
  }
  sectionchange(tabcontent) {
    const inputFields = this.template.querySelectorAll("lightning-input-field");
    if (inputFields) {
      inputFields.forEach((field) => {
        for (var i = 0; i < this.mapping.length; i++) {
          if (field.name == this.mapping[i].name) {
            this.mapping[i].value = field.value;
          }
        }
      });
    }
    if (tabcontent) this.query.tabcontent = tabcontent;
  }

  handleSaveArticle(event) {
    this.valid = true;
    this.publishrecords = false;
    let fieldMap = event.detail.fields;
    if (!this.showSection) {
      let arr = Object.keys(fieldMap);
      this.mapping.map((res) => {
        if (arr.includes(res.name)) {
          res.value = fieldMap[res.name];
        } else {
          if (res.mandatory && res.value == "") {
            this.valid = false;
          }
          fieldMap[res.name] = res.value;
        }
      });
      let queryData = this.query;
      if (queryData.tabcontent == 1) {
        queryData.tabcontent = 0;
      }
      this.query = {};
      this.query = { ...queryData };
    } else {
      let arr = Object.keys(fieldMap);
      this.mapping.map((res) => {
        if (arr.includes(res.name)) {
          res.value = fieldMap[res.name];
        } else {
          if (res.mandatory && res.value == "") {
            this.valid = false;
          }
          fieldMap[res.name] = res.value;
        }
      });
    }
    fieldMap["OwnerId"] = this.userId;
    this.template.querySelector("lightning-record-edit-form").submit(fieldMap);
    this.boolSave = true;
    this.showloader = false
    this.displayDuplicacyModal = false
    this.saveProgModalView(this.boolSave);
  }

  stopEnter = (event) => {
    const target = event.target;
      if (target.closest('[data-exclude-stopenter="true"]')) {
      return;
    }
      if (event.which === 13) {
      event.preventDefault();
      event.stopPropagation();
    }
  };
  //Publish and schedule method calls
  async saverecord() {
    if (this.dataCategories.length) {
      await this.saveCategories();
    }
    if (!this.iseditarticle) {
      getArticleNumber({ articleid: this.articleId })
        .then((result) => {
          this.articlenumber = result;
          var sendData = {
            articleid: this.articleId,
            articlenumber: this.articlenumber,
            url: `${window.location.origin}/lightning/r/${this.destobj}/${this.articleId}/view`,
            title: this.fieldset.Title,
            articleStatus: this.iseditarticle ? 'Updated' : 'Created',
            recordTypeId: this.recordtypeID
          };
          knowblerPubsub.fireEvent(
            this.objpageReference,
            "publishingarticle" + this.newnumber,
            sendData
          );
        })
        .catch(error => { this.template.querySelector(this.knowblerModalComponent).showError(error); })
      this.publishmethods();
    } else if (this.iseditarticle) {
      getArticleNumber({ articleid: this.articleId })
        .then((result) => {
          this.articlenumber = result;
          var sendData = {
            articleid: this.articleId,
            articlenumber: this.articlenumber,
            url: `${window.location.origin}/lightning/r/${this.destobj}/${this.articleId}/view`,
            title: this.fieldset.Title,
            articleStatus: this.iseditarticle ? 'Updated' : 'Created',
            recordTypeId: this.recordtypeID
          };
          knowblerPubsub.fireEvent(
            this.objpageReference,
            "publishingarticle" + this.newnumber,
            sendData
          );
        })
        .catch(error => { this.template.querySelector(this.knowblerModalComponent).showError(error); })
      this.updatingrecords = true;
      this.publishmethods();
    }
  }

  publishmethods() {
    if (!this.isschedulepublish) {
      //Publish method call
      PublishArticle({ articleId: this.articleId })
        .then((result) => {
          //Successfully published popup
          this.template
            .querySelector(this.knowblerModalComponent)
            .ispublishnowmethod();
        })
        .catch((error) => {
          // this.template.querySelector('c-knowbler-modal-component').showError(error.body.message);
          const event = new ShowToastEvent({
            title: "error in publish!",
            message: error.body.message
          });
          this.dispatchEvent(event);
        });
    }
    if (this.isschedulepublish) {
      //Schedule Method call
      ScheduleArticle({
        articleId: this.articleId,
        scheduledDate: this.scheduledate
      })
        .then((result) => {
          //Successfully published popup
          this.template
            .querySelector(this.knowblerModalComponent)
            .ispublishschedulenowmethod();
        })
        .catch((error) => {
          //this.template.querySelector('c-knowbler-modal-component').showError(error.body.message);
          const event = new ShowToastEvent({
            title: "error in schedule!",
            message: error.body.message
          });
          this.dispatchEvent(event);
        });
    }
  }

  //Publish and attach method calls
  async saveandattachrecord() {
    if (this.dataCategories.length) {
      await this.saveCategories();
    }
    if (!this.iseditarticle) {
      getArticleNumber({ articleid: this.articleId })
        .then((result) => {
          this.articlenumber = result;
          this.publishattachmethods();
        })
        .catch(error => {
          this.template.querySelector(this.knowblerModalComponent).showError(error);
        })

    }

    else if (this.iseditarticle) {
      this.updatingrecords = true;
      getArticleNumber({ articleid: this.articleId })
        .then((result) => {
          this.articlenumber = result;
          this.publishattachmethods();
        })
        .catch(error => { this.template.querySelector(this.knowblerModalComponent).showError(error); })
    }
  }

  async publishattachmethods() {
    let articleSharingUrl = "";
    if (this.clientSettings && this.clientSettings.base_href) {
      let res = await GetArticleFields({
        recordId: this.articleId,
        destinationObj: this.destobj
      });
      articleSharingUrl = this.createCustomUrl(res);
    } else {
      articleSharingUrl =
        window.location.origin +
        "/lightning/r/" +
        this.destobj +
        "/" +
        this.articleId +
        "/view";
    }

    if (!this.isschedulepublish) {
      PublishArticle({ articleId: this.articleId }).then((result) => {
        this.attachtocase(this.articleId, this.caseid, articleSharingUrl);
      }).catch(error => {
        this.template.querySelector(this.knowblerModalComponent).showError(error.body.message);
      })
    }
    //Successfully published and attach popup
    if (this.isschedulepublish) {
      var sendData = {
        articleid: this.articleId,
        articlenumber: this.articlenumber,
        url: articleSharingUrl,
        title: this.fieldset.Title,
        articleStatus: this.iseditarticle ? 'Updated' : 'Created',
        recordTypeId: this.recordtypeID
      };
      knowblerPubsub.fireEvent(this.objpageReference, "createattach" + this.newnumber, sendData);
      this.template.querySelector(this.knowblerModalComponent).isattachschedulemethod();
    }
  }

  attachtocase(articleid, caseid, articleSharingUrl) {
    AttachArticleToCase({ articleId: articleid, caseId: caseid })
      .then((result) => {
        // Successfully published and attach popup
        const sendData = {
          articleid,
          articlenumber: this.articlenumber,
          caseid: this.casenumber,
          url: articleSharingUrl,
          title: this.fieldset.Title,
          resolution: this.isresolution,
          reference: this.isreference,
          articleStatus: this.iseditarticle ? 'Updated' : 'Created',
          recordTypeId: this.recordtypeID
        };
        knowblerPubsub.fireEvent(
          this.objpageReference,
          `publishattacharticle${this.newnumber}`,
          sendData
        );

      this.template.querySelector(this.knowblerModalComponent).isattachmethod();
    }).catch(error => {

      this.template.querySelector(this.knowblerModalComponent).showError(error.body.message);
    })
  }
  //landing back to articleList page
  handlepublish(event) {
    this.activevalue = event.detail;
    this.handleLeave();
  }

  handleBackLeave() {
    if (this.uploadedFiles?.length) {
      for (const file of this.uploadedFiles) {
        this.deleteFile(file.documentId);
      }
    }
    this.displayTitleLoader = false;
    this.displaySummaryLoader = false;
    let tempGenerateSummary = { ...this.generateSummaryFields };
    Object.keys(tempGenerateSummary).forEach((field) => {
      tempGenerateSummary[field] = false;
    })

    this.generateSummaryFields = { ...tempGenerateSummary };
    if (this.fromBack) {
      this.fromBack = false;
      var eventback = new CustomEvent("back", {
        detail: this.mapping
      });
      this.dispatchEvent(eventback);
    } else {
      this.dispatchEvent(new CustomEvent("leave"));
    }
  }
  handleLeave() {
    if (!this.iseditarticle) {
      var eventSend = new CustomEvent("leave", {
        detail: { mapping: this.mapping, activevalue: this.activevalue }
      });

    }
    else if (this.iseditarticle && (!this.updatingrecords)) {
      var eventSend = new CustomEvent("leave", {
        detail: {
          Id: this.myRecordId,
          mapping: this.mapping,
          activevalue: this.activevalue
        }
      });
    } else if (this.updatingrecords) {
      var eventSend = new CustomEvent("leave", {
        detail: { mapping: this.mapping, activevalue: this.activevalue }
      });

    }


    //this.dispatchEvent(activeevent);
    this.dispatchEvent(eventSend);
  }

  handleBack() {
    this.fromBack = true;
    this.showAlertModal();
  }
  handleError(event) {
    this.showloader = false;
    this.closePublishModal();
    this.boolSave = false;
    this.saveProgModalView(this.boolSave);
    if(event.detail && event.detail.message && typeof event.detail.message === 'object') {
      event.detail.message = event.detail.message?.error && event.detail.message?.error == 'Received exception event aura:systemError from server' ? "Unable to process your request" : event.detail.message?.error || "Unable to process your request";
    }
    this.template.querySelector(this.knowblerModalComponent).showError(event);

  }
  @api async handleSuccess(event) {
    let caseDetail = event.detail;
    this.articleId = caseDetail.id;
    if (!this.iseditarticle && this.uploadedFiles?.length) {
      await this.handleUploadFile(this.articleId);
    }
    if (!this.publishrecords) {
      getArticleNumber({ articleid: caseDetail.id })
        .then((result) => {
          this.articlenumber = result;
          var sendData = {
            articleid: caseDetail.id,
            articlenumber: this.articlenumber,
            url:
              window.location.origin +
              "/lightning/r/" +
              this.destobj +
              "/" +
              caseDetail.id +
              "/view",
            title: caseDetail?.fields?.Title?.value,
            articleStatus: this.iseditarticle ? 'Updated' : 'Created',
            recordTypeId: caseDetail.recordTypeId,
          };
          knowblerPubsub.fireEvent(
            this.objpageReference,
            "createarticle" + this.newnumber,
            sendData
          );
        })
        .catch(error => { this.template.querySelector(this.knowblerModalComponent).showError(error); })

      this.myRecordId = event.detail.id;
      this.mapping.push({
        name: "lastModifiedDate",
        value: event.detail.lastModifiedDate
      });

      this.uploadCheck = false;
      if (this.dataCategories.length) {
        this.saveCategories();
      } else {
        this.afterSuccess();
      }
    } else if (this.publishrecords) {
      switch (this.publishmethod) {
        case "publish":
          this.saverecord();
          break;
        case "attach":
          this.saveandattachrecord();
          break;
        default:
        // code block
      }
    }
  }
  @api async afterSuccess() {
    await this.sleep(3000);
    this.boolSave = false;
    this.saveProgModalView(this.boolSave);
    if (!this.iseditarticle)
    {
      this.template.querySelector(this.knowblerModalComponent).showSuccess({ type: 'create', message: 'Article Created Successfully' });
    }
      else if (this.iseditarticle)
     {
      this.template.querySelector(this.knowblerModalComponent).showSuccess({ type: 'update', message: 'Article Updated Successfully' });
  }
     await this.sleep(3000);
    this.handleLeave();
  }
  saveCategories = async () => {
    await updateDataCategory({
      categories: this.dataCategories,
      recordId: this.articleId
    }).then(result => {
      if (!this.publishrecords) {
        this.afterSuccess()
      }
    }).catch(error => {
      this.template.querySelector(this.knowblerModalComponent).showError(error);
      this.boolSave = false;
      this.saveProgModalView(this.boolSave);

    });
  }
  sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
  saveProgModalView(flagSave) {
    if (flagSave) {
      this.progressflag = true;
    } else {
      this.progressflag = false;
    }
  }

  showAlertModal() {
    this.stayleaveflag = true;
    this.template.querySelector(this.knowblerModalComponent).check();
  }

  handleChangeCheck(){
    for(let i=0;i<this.contentHealthCheckArray.length;i++){
      if(this.fieldset){
        if(!(this.fieldset[this.contentHealthCheckArray[i]] && this.fieldset[this.contentHealthCheckArray[i]].trim().length>0)){
          return false;
        }
      }
    }
    return true;
  }
  //On change event handle for fields
  handleChange(event) {
    if (event === "setValue") {
      for (let i = 0; i < this.mapping.length; i++) {
        if (this.mapping[i] && this.mapping[i].value) {
          this.fieldset[this.mapping[i].name] = this.mapping[i].value;
        }
      }
      this.isValueChange = true;

      return;
    }
    var currField = (event?.currentTarget?.dataset?.name) ? (event?.currentTarget?.dataset?.name) : event
    if (currField === 'Title') {
      const inputFieldURL = this.template.querySelector('lightning-input-field[data-name="URL Name"]');
      inputFieldURL = null
      let splChars = /[^a-zA-Z0-9-]+/;
      var target;
      if (event.target) target = event.target.value;
      else {
        let ob = this.mapping.find((res) => res.name == "Title");
        target = ob.value;
      }
      this.fieldset['Title']=target;
      var str = target.split(splChars).join('-').replace(new RegExp('[-]+$|^[-]+'), '').replace(new RegExp('[-]+$|^[-]'), '');
      let urlOb = this.mapping.find(res => res.name == 'UrlName')
      if (urlOb)
        urlOb.value = str;
      this.fieldset['UrlName']= urlOb.value;
      const inputFields = this.template.querySelectorAll('lightning-input-field');
      if (inputFields) {
        let isTitle = false;
        for (let i = 0; i < inputFields.length; i++) {
          if(inputFields[i].name ==='Title'){
            inputFields[i].reportValidity();
            if (inputFields[i].value.length) {
              isTitle = true;
            }
          }
          if(inputFields[i].name === 'UrlName' && !isTitle){
            inputFields[i].reportValidity();
            if (inputFields[i].querySelector("lightning-input")) {
              let obb = inputFields[i].querySelector("lightning-input");
              obb.className = obb.className.replace("slds-has-error", "");
            }
          }
        }
      }
    }
    if (event !== 'Title') {
      this.fieldset[event.target.name] = event.target.value;
    }
    this.isValueChange = true;
    this.populateContentHealthCheck();
    this.checkEmptyValidator = this.handleChangeCheck();
  }

  handleCloseFile() {
    this.uploadedFiles = [];
    this.uploadCheck = false;
  }
  changeValue(value, fieldname) {
    this.mapping.map(res => {
      if (res.name == fieldname)
        res.value = value;
    })
    this.fieldset[fieldname]=value;

  }

  //Toggle publish menu
  showmenu() {
    this.template.querySelector(".menuitems").style.display = "block";
    this.template.querySelector(".upicon").style.display = "flex";
    this.template.querySelector(".downicon").style.display = "none";
  }
  hidemenu() {
    this.template.querySelector(".menuitems").style.display = "none";
    this.template.querySelector(".upicon").style.display = "none";
    this.template.querySelector(".downicon").style.display = "flex";
  }
closeDuplicacyModal() {
    this.displayDuplicacyModal = false;
  }
  hideScreen() {
    this.articleListData.showEditDetailPage = false;
    this.articleListData.showDetailPage = false;
    this.articleListData.showEditPage = false;
    this.firstTimeHit = true;
    this.articleListData.createArtcleMapping = {};
  }
  openManageScreen(event) {
    try{
      this.recordt = event.detail.item?.RecordType?.Name;
      this.articleListData.createArtcleMapping = {};
      this.articleListData.showEditDetailPage = true;
      this.articleListData.currentId = event.detail?.item?.Id;
      this.articleListData.detailArticle = { ...event.detail?.item };
      this.articleListData.mappingFields = [...[]];
      if (
        this.kcssupport.length == 1 &&
        this.kcssupport[0].salesforceExperience == 'Classic'
      ) {
        this.articleListData.configRecord = this.kcssupport;
      } else if (
        this.kcssupport &&
        this.kcssupport.length &&
        this.kcssupport[0].RecordType &&
        this.kcssupport[0].RecordType === 'master' &&
        !this.articleListData.detailArticle?.RecordType?.Name
      ) {
        this.articleListData.configRecord = this.kcssupport;
      } else {
        this.articleListData.configRecord = this.kcssupport.filter(
          (res) =>
            res?.RecordType ==
              this.articleListData.detailArticle?.RecordType?.Name && res.active
        );
      }
      if (this.articleListData.configRecord.length) {
        this.recordt = this.articleListData?.detailArticle?.RecordType?.Name
          ? this.articleListData.detailArticle?.RecordType?.Name
          : 'master';
        this.articleListData.flagForm = false;
        this.articleListData.configRecord[0].mapping.map((res) => {
          if (res.type == 'file') {
            this.articleListData.mappingFields.push(
              `${
                this.articleListData.configRecord[0].DestinationObject
              }.${res.name.replace('__c', '')}__Name__s`
            );
            this.articleListData.mappingFields.push(
              `${
                this.articleListData.configRecord[0].DestinationObject
              }.${res.name.replace('__c', '')}__Length__s`
            );
            this.articleListData.mappingFields.push(
              `${
                this.articleListData.configRecord[0].DestinationObject
              }.${res.name.replace('__c', '')}__Body__s`
            );
            this.articleListData.mappingFields.push(
              `${
                this.articleListData.configRecord[0].DestinationObject
              }.${res.name.replace('__c', '')}__ContentType__s`
            );
          } else
            this.articleListData.mappingFields.push(
              `${this.articleListData.configRecord[0].DestinationObject}.${res.name}`
            );
        });
      } else {
        this.recordt = this.articleListData?.detailArticle?.RecordType?.Name
          ? this.articleListData.detailArticle?.RecordType?.Name
          : 'master';
        this.articleListData.flagForm = true;
      }
      if (event.detail?.isEdit) {
        this.articleListData.isedit = true;
        this.showDetailPage = false;
      } else {
        this.articleListData.isedit = false;
      }
      if (event.detail?.showManage) {
        this.articleListData.showDetailPage = true;
      } else {
        this.articleListData.showEditPage = true;
        this.articleListData.showDetailPage = false;
      }
    }catch(err){
      console.log("err------------", err)
    }
  }
  dotClick(event) {
    //     console.log('event in cards',event);
    if (!event) return;
    this.articlesData = this.articlesData.map((elm) => {
      if (
        event?.detail?.ArticleNumber &&
        elm.ArticleNumber == event.detail?.ArticleNumber
      )
        elm.showDropdown = !elm.showDropdown;
      else elm.showDropdown = false;
      return elm;
    });
    // console.log('article data in cards*',this.articlesData);
  }
  closeOptionsDropdown(){
    this.dotClick({detail: this.item})
  }
  previewOpen() {}
  gotohome() {
    this.dispatchEvent(new CustomEvent("gotohome"));
  }
  proceedAnyway() {
    if (this.proceedAnywayAction === "save-as-draft") {
      this.handleSaveArticle(this.saveAsDraftEvent);
    } else if (this.proceedAnywayAction === "publish") this.handlePublish();
    else this.handlePublishAttach();
  }
  async checkDuplicateArticles(event) {
    this.saveAsDraftEvent = event;
    this.proceedAnywayAction = event.target.dataset.id;
    event.preventDefault();
    // setArticleStatusProceedAnyway(articleStatus);
    try {
      let description = [];
      for (let i = 0; i < this.mapping.length; i++) {
        const value = this.fieldset[this.mapping[i].name]
        if (this.mapping[i]?.checkHealth && this.mapping[i].name !== "Title" && value) {
          description.push(value);
        }
      }
      const dataCategory = JSON.parse(this.alldatacategories);
      const selectedDataCategory = JSON.parse(JSON.stringify(this.dataCategories)).length ? JSON.parse(this.dataCategories) : [];
      let attachCategoryPath = [];
      let finalCategoryTree;
      for (const val of selectedDataCategory) {
        for (const iterator of dataCategory.categoryGroups) {
          if (iterator.topCategories && val.categoryGroup === iterator.name) {
            for (const root of iterator.topCategories) {
              root.label = "All";
              root.name = "All"
              let path = this.findPath(root, val.name);
              path.splice(1, 0, val.categoryGroup);
              attachCategoryPath.push(path);
            }
          }
        }
      }


      if(attachCategoryPath && attachCategoryPath.length) {
        attachCategoryPath.forEach(val => {
          if (finalCategoryTree) {
            const resultTree = this.addBranchIntoTree(
              val,
              finalCategoryTree
            );
            finalCategoryTree = resultTree;
          } else {
            let obj = {
              name: val[
                val.length - 1
              ],
              childCategories: []
            };
            val[
              val.length - 1
            ] = obj;
            let z = val.length - 1;
            while (z > 0) {
              obj = {
                name: val[z - 1],
                childCategories: [val[z]]
              };
              val[z - 1] = obj;
              val.pop();
              z -= 1;
            }
            finalCategoryTree = val;
          }
        })
      }
      let articleNumber = '';
      if (this.currentid)
        articleNumber = await getArticleNumber({
          articleid: this.currentid
        });
      const requestOptions = {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          authorization: window.token
        },
        body: JSON.stringify({
          id: articleNumber || "",
          uid: this.clientSettings.uid,
          title: this.fieldset["Title"],
          description: description.join(" "),
          categories: finalCategoryTree ? finalCategoryTree[0] : {},
        })
      };
      const result = await fetch(
        `${this.endpoint}/kcs-anlytics/rest/anlytics/duplicacy-checker/check-duplicate-articles`,
        requestOptions
      ).then((response) => response.json());
      this.showloader = false;
      const duplicatedArticlesList = result?.response?.data;
      if (duplicatedArticlesList?.length <= 0 || !duplicatedArticlesList) {
        this.proceedAnyway()
        return;
      }
      this.cardLength = duplicatedArticlesList.length;
      const articleNumbers = duplicatedArticlesList.map((obj) => obj.id);
      const allRecords = await getRecordDetailsWithNumbers({ articleNumbers, objName: this.destobj });

      // Create a Map to store the latest article for each ArticleNumber
      const latestArticlesMap = new Map();

      for (const article of allRecords) {
        const articleNumber = article.ArticleNumber;
        const lastModifiedDate = new Date(article.LastModifiedDate); // Convert to Date object

        // Check if Map already has an entry for the ArticleNumber
        if (!latestArticlesMap.has(articleNumber) || lastModifiedDate > latestArticlesMap.get(articleNumber).LastModifiedDate) {
          latestArticlesMap.set(articleNumber, article);
        }
      };
      const uniqueRecords = Array.from(latestArticlesMap.values());
      const recordsWithScores = uniqueRecords.map((item, index)=>({...item, duplicacyPercentage: (duplicatedArticlesList.find(item2=> item2.id === item.ArticleNumber)?.score * 100).toFixed(2) }));
      this.articlesData = recordsWithScores.sort((a, b) => {
          if (b.duplicacyPercentage !== a.duplicacyPercentage) {
              return b.duplicacyPercentage - a.duplicacyPercentage;
          } else if (b.PublishStatus !== a.PublishStatus) {
              return b.PublishStatus === 'Online' ? 1 : -1;
          } else {
            const bDate = new Date(b.LastModifiedDate)
            const aDate = new Date(a.LastModifiedDate)
            return bDate - aDate
          }
      });
      if (duplicatedArticlesList?.length > 0) {
        this.displayDuplicacyModal = true;
        const maximize = localStorage.getItem("knowbler_maximize");
        const window_inner_height = localStorage.getItem("knowbler_window_innerheight");
        
        if (+window_inner_height > 500 && maximize === "true") {
          if (+window_inner_height < 580) {
            setTimeout(() => {
              if (this.template.querySelector(".knowbler__zendesk-articles-list")) {
                this.template.querySelector(".knowbler__zendesk-articles-list").style.maxHeight = "350px";
              }
            }, 100)
          } else if (+window_inner_height < 610) setTimeout(() => {
            if (this.template.querySelector(".knowbler__zendesk-articles-list")) {
                this.template.querySelector(".knowbler__zendesk-articles-list").style.maxHeight = "380px";
            }
          }, 100)
          else if (+window_inner_height < 700) setTimeout(() => {
            if (this.template.querySelector(".knowbler__zendesk-articles-list")) {
                this.template.querySelector(".knowbler__zendesk-articles-list").style.maxHeight = "390px";
            }
          }, 100)
          else {
            setTimeout(() => {
              if (this.template.querySelector(".knowbler__zendesk-articles-list")) {
                this.template.querySelector(".knowbler__zendesk-articles-list").style.maxHeight = "";
              }
            }, 100)
          }
        }
        if(maximize === "true")
          setTimeout(()=>{
            if (this.template.querySelector(".knowbler__zendesk-articles-list")) {
              this.template.querySelector(".knowbler__zendesk-articles-list").classList.add('maximize');
            }
            if (this.template.querySelector(".knowbler__salesforce-alert-popup-dialog")) {
              this.template.querySelector(".knowbler__salesforce-alert-popup-dialog").classList.add('maximize');
            }
          }, 100)
        return;
      }
    } catch (err) {
      this.showloader = false;
      this.template
          .querySelector(this.knowblerModalComponent)
          .showError(err);
    }
  }
  //Publish and attach menu dropdown
  handlePublish() {
    if (this.fieldset["Title"] == "" || this.fieldset["UrlName"] == "") {
      this.template.querySelectorAll(".formInp").forEach((element) => {
        element.reportValidity();
      });
      this.template
      .querySelector(this.knowblerModalComponent)
      .showError({ body: { message: 'Required fields are missing.' } });
    }
    else {
      canPublishArticles()
        .then((result) => {
          this.showloader = false
          this.displayDuplicacyModal = false
          if (result) {
            this.isPublish = true;
          } else {
            this.template
              .querySelector(this.knowblerModalComponent)
              .showError('you dont have the permission');
          }
        })
        .catch((error) => {
          this.template
            .querySelector(this.knowblerModalComponent)
            .showError(error);
        });
    }
    this.hidemenu();
  }

  handlePublishAttach() {
    if (this.fieldset["Title"] == "" || this.fieldset["UrlName"] == "") {
      this.template.querySelectorAll(".formInp").forEach((element) => {
        element.reportValidity();
      });
      this.template
      .querySelector('c-knowbler-modal-component')
      .showError({ body: { message: 'Required fields are missing.' } });
    } else {
      canPublishArticles()
        .then((result) => {
          this.showloader = false
          this.displayDuplicacyModal = false
          if (result) {
            this.isPublish = true;
            this.ispublishattach = true;
            if (!this.iseditarticle)
              this.caseid = this.casedata['Id'];
          } else {
            this.template
              .querySelector(this.knowblerModalComponent)
              .showError('you dont have the permission');
          }
        })
        .catch((error) => {
          this.template
            .querySelector(this.knowblerModalComponent)
            .showError(error);
        });
    }
    this.hidemenu();
  }



  publisharticlepermissioncheck()
  {
    canPublishArticles().then(result=>
    {
      if(result)
      {
        this.permissiontopublish = true;
        this.saverecord(this.fieldset);
      }else{
        this.permissiontopublish = false;
        this.template.querySelector(this.knowblerModalComponent).showError('you dont have the permission to publish or attach articles');}
    })
    .catch(error =>{this.template.querySelector(this.knowblerModalComponent).showError(error);})
  }

  closePublishModal() {
    this.isPublish = false;
    this.ispublishattach = false;
  }

  @api
  autoGenTitle(data, summaryData, retryPopup, time = 1) {
    if (this.displayTitleLoader || this.displaySummaryLoader) {
      let config = JSON.parse(JSON.stringify(this.kcssupport));
      if (typeof summaryData === 'object' && summaryData !== null) {
        for (let index = 0; index < config.length; index++) {
          if (config[index].RecordType == this.recordtype) {
            const mapConfig = config[index].autoGenConfig.config;
            const summaryDataObjKeys = Object.keys(summaryData);
            const mapConfigFields = mapConfig.map(config => config.field);
            const missing = mapConfigFields.filter(key => key !== 'Title' && !summaryDataObjKeys.includes(key));

            if (missing && missing.length) {
              this.template.querySelector(this.knowblerModalComponent).showOpenApiError(2);
              break;
            }
          }
        }
      }
      if (data === 'API Error' || summaryData === 'API Error') {
        if(retryPopup) {
          this.template.querySelector(this.knowblerModalComponent).showOpenApiRetryError();
        } else {
          if (summaryData === 'contextLimitReached') {
            this.template.querySelector(this.knowblerModalComponent).showOpenApiError(1);
          } else {
            this.template.querySelector(this.knowblerModalComponent).showOpenApiError();
          }
        }
        this.displayTitleLoader = false;
        this.displaySummaryLoader = false;
        let tempGenerateSummary={...this.generateSummaryFields};
        Object.keys(tempGenerateSummary).forEach((field)=>{
          tempGenerateSummary[field]=false;
        })
        // Object.keys(this.generateSummaryFields).forEach((field)=>{
        //   this.generateSummaryFields[field]=false;
        // })
        this.generateSummaryFields={...tempGenerateSummary};
        return;
      }

      config.forEach((element) => {
        if (element.RecordType == this.recordtype) {
          const mappingConfig = element.autoGenConfig.config;
          if (this.mapping.length && mappingConfig.length) {
            for (let i = 0; i < this.mapping.length; i++) {
              if (this.mapping[i].autoGen) {
                const existingPacket = mappingConfig.find(
                  (item) => item.field === this.mapping[i].name
                );
                if (existingPacket) {
                  if (
                    existingPacket.generateType === 'titleGeneration' &&
                    this.displayTitleLoader
                  ) {
                    if (this.mapping[i].isRichTextArea) {
                      const contentWithBr = data.replace(/\n/g, '<br>');
                      this.mapping[i].value = contentWithBr;
                      this.mapping[i].label = existingPacket.label;
                      this.mapping[i].sectionLabel =
                        existingPacket.sectionLabel;
                      this.fieldset[this.mapping[i].name] = contentWithBr;
                    } else {
                      this.mapping[i].value = data;
                      this.mapping[i].label = existingPacket.label;
                      this.mapping[i].sectionLabel =
                        existingPacket.sectionLabel;
                      this.fieldset[this.mapping[i].name] = data;
                      if (this.mapping[i].name === "Title") {
                        this.handleChange("Title");
                      }
                    }
                    this.displayTitleLoader = false;
                  } else if (
                    existingPacket.generateType != 'titleGeneration' &&
                    this.generateSummaryFields.hasOwnProperty(existingPacket.generateType)
                    // this.displaySummaryLoader
                  ) {
                    if (this.mapping[i].isRichTextArea) {
                      const contentWithBr = summaryData[existingPacket.generateType].replace(/\n/g, '<br>');
                      this.mapping[i].value = contentWithBr;
                      this.mapping[i].label = existingPacket.label;
                      this.mapping[i].sectionLabel =
                        existingPacket.sectionLabel;
                      this.fieldset[this.mapping[i].name] = contentWithBr;
                    } else {
                      this.mapping[i].value = summaryData[existingPacket.generateType];
                      this.mapping[i].label = existingPacket.label;
                      this.mapping[i].sectionLabel =
                        existingPacket.sectionLabel;
                      this.fieldset[this.mapping[i].name] = summaryData[existingPacket.generateType];
                      if (this.mapping[i].name === "Title") {
                        this.handleChange("Title");
                      }
                    }
                    let tempFieldSummary={...this.generateSummaryFields};
                    tempFieldSummary[existingPacket.generateType] = false;
                    this.generateSummaryFields = { ...tempFieldSummary};

                    // this.generateSummaryFields[existingPacket.generateType] = false;
                    this.displaySummaryLoader=false;
                  }
                  this.handleChange('setValue');
                  if (this.mapping[i].value) {
                    this.titleGenerated = true;
                    setTimeout(() => {
                      this.titleGenerated = false;
                    }, 3000);
                  }
                  }
                }
              }
            } else {
              setTimeout(() => {
                if (time === 1) {
                  this.autoGenTitle(data, summaryData, retryPopup, time + 1);
                }
              }, 1000);
            }
          }
      });
    }
  }

  cancelTitleGeneration() {
    this.displayTitleLoader = false;
    this.displaySummaryLoader = false;
    // Object.keys(this.generateSummaryFields).forEach((field)=>{
    //   this.generateSummaryFields[field]=false;
    // })
    let tempGenerateSummary = { ...this.generateSummaryFields };
    Object.keys(tempGenerateSummary).forEach((field) => {
      tempGenerateSummary[field] = false;
    })
    this.generateSummaryFields = { ...tempGenerateSummary };
  }

  get saveButtonClass() {
    const defaultClasses =  this.displayTitleLoader || this.displaySummaryLoader
      ? 'topBarSave knowbler__disable-article-save-button'
      : 'topBarSave';
      const disabledClass = this.fieldset['Title']?.trim().length <= 0 ||
      this.fieldset['UrlName']?.trim().length <= 0 ? ' disabled':''
    return defaultClasses + disabledClass
  }

 publishnow()
  {
    this.publishrecords = true;
    this.publisharticlemethods("publish");
    //this.saverecord(this.fieldset);
  }
  schedulepublish(event) {
    this.publishrecords = true;
    var SubADay = new Date(event.detail);
    SubADay.setDate(SubADay.getDate() - 1);
    this.scheduledate = SubADay;

    this.scheduledate = event.detail;
    this.isschedulepublish = true;
    this.publisharticlemethods("publish");
    // this.saverecord(this.fieldset);

  }
  //Publish and attach articles
  referencenow() {
    this.publishrecords = true;
    this.isreference = true;
    if (this.namespace) {
      this.fieldset[this.namespace + "__Article_Type__c"] = "Reference";
    } else {
      this.fieldset["Article_Type__c"] = "Reference";
    }
    if (!this.iseditarticle) {
      if (this.namespace) {
        this.fieldset[this.namespace + "__Case_Id__c"] = this.casedata["Id"];
      } else {
        this.fieldset["Case_Id__c"] = this.casedata["Id"];
      }
    } else {
      if (this.namespace) {
        this.fieldset[this.namespace + "__Case_Id__c"] = this.caseid;
      } else {
        this.fieldset["Case_Id__c"] = this.caseid;
      }
    }


    this.publisharticlemethods('attach');
  }
  resolutionnow() {
    this.publishrecords = true;
    this.isresolution = true;

    if(this.namespace){this.fieldset[this.namespace+'__Article_Type__c']='Resolution'};
    if(!this.iseditarticle){
    if(this.namespace){this.fieldset[this.namespace+'__Case_Id__c']=this.casedata['Id'];}
    else{this.fieldset['Case_Id__c']=this.casedata['Id'];}
    }
    else{
      if(this.namespace){this.fieldset[this.namespace+'__Case_Id__c']=this.caseid;}
    else{this.fieldset['Case_Id__c']=this.caseid;}
    }

    // this.saveandattachrecord(this.fieldset);
    this.publisharticlemethods("attach");
  }

  // Schedule articles for publish and attach
  referenceschedule(event) {
    this.publishrecords = true;
    var SubADay = new Date(event.detail);
    SubADay.setDate(SubADay.getDate() - 1);
    this.scheduledate = SubADay;

    let dateTime = this.scheduledate;
     let date = `${dateTime.getFullYear()}-${dateTime.getMonth()+1}-${dateTime.getDate()}`;
    this.isschedulepublish = true;
    if(this.namespace){this.fieldset[this.namespace+'__Article_Type__c']='Reference';}
    else{this.fieldset['Article_Type__c']='Reference';}
    if(!this.iseditarticle){
    if(this.namespace){this.fieldset[this.namespace+'__Case_Id__c']=this.casedata['Id'];}
    else{this.fieldset['Case_Id__c']=this.casedata['Id'];}
    }
    else{
      if(this.namespace){this.fieldset[this.namespace+'__Case_Id__c']=this.caseid;}
    else{this.fieldset['Case_Id__c']=this.caseid;}
    }
      if(!this.iseditarticle){
    if(this.namespace){this.fieldset[this.namespace+'__Schedule_Date__c']=date;}
    else{this.fieldset.Schedule_Date__c=date;}}
    else
    {
       if(this.namespace){this.fieldset[this.namespace+'__Schedule_Date__c']=date;}
    else{this.fieldset['Schedule_Date__c']=date;}
    }

    // this.saveandattachrecord(this.fieldset)
    this.publisharticlemethods('attach');
  }
  resolutionschedule(event){
    this.publishrecords = true;
    var SubADay = new Date(event.detail);
    SubADay.setDate(SubADay.getDate()-1);
    this.scheduledate = SubADay;
    let dateTime = this.scheduledate;
     let date = `${dateTime.getFullYear()}-${dateTime.getMonth()+1}-${dateTime.getDate()}`;
    this.isschedulepublish = true;
    if(this.namespace){this.fieldset[this.namespace+'__Article_Type__c']='Resolution';}
    else{this.fieldset['Article_Type__c']='Reference';}
    if(!this.iseditarticle){
    if(this.namespace){this.fieldset[this.namespace+'__Case_Id__c']=this.casedata['Id'];}
    else{this.fieldset['Case_Id__c']=this.casedata['Id'];}
    }
    else{
      if(this.namespace){this.fieldset[this.namespace+'__Case_Id__c']=this.caseid;}
    else{this.fieldset['Case_Id__c']=this.caseid;}
    }
    if(!this.iseditarticle){
    if(this.namespace){this.fieldset[this.namespace+'__Schedule_Date__c']=date;}
    else{this.fieldset['Schedule_Date__c']=date;}}

    // this.saveandattachrecord(this.fieldset)
    this.publisharticlemethods("attach");
  }

  // uniqueArticleFields(templateData) {
  //   const titleGenerationConfig = templateData.autoGenConfig.config.find(
  //     (config) => config.generateType === 'titleGeneration'
  //   );
  //   const summaryGenerationConfig = templateData.autoGenConfig.config.find(
  //     (config) => config.generateType === 'summaryGeneration'
  //   );

  //   const titleCaseFields = titleGenerationConfig
  //     ? titleGenerationConfig.caseFields
  //     : [];
  //   const summaryCaseFields = summaryGenerationConfig
  //     ? summaryGenerationConfig.caseFields
  //     : [];

  //   const uniqueCaseFields = Array.from(
  //     new Set([...titleCaseFields, ...summaryCaseFields])
  //   );

  //   return uniqueCaseFields;
  // }

  uniqueArticleFields(templateData) {
    const titleGenerationConfig = templateData?.autoGenConfig?.config.find(
      (config) => config.generateType === 'titleGeneration'
    );
    // const summaryGenerationConfig = templateData.autoGenConfig.config.find(
    //   (config) => config.generateType === 'summaryGeneration'
    // );

    const nonTitleGenerationConfig = templateData?.autoGenConfig?.config.filter(
      (configLLM) => configLLM.generateType != 'titleGeneration'
    );
    let nonTitleCaseFields = [];
    nonTitleGenerationConfig.forEach(i=>nonTitleCaseFields.push(...i.caseFields));

    const titleCaseFields = titleGenerationConfig
      ? titleGenerationConfig.caseFields
      : [];
    // const summaryCaseFields = summaryGenerationConfig
    //   ? summaryGenerationConfig.caseFields
    //   : [];

    const uniqueCaseFields = Array.from(
      new Set([...titleCaseFields, ...nonTitleCaseFields])
    );

    return uniqueCaseFields;
  }

  async createAutoGenerationPayload() {
    // const caseNumber = this.casenumber;
    const mapping = JSON.parse(
      JSON.stringify(
        this.kcssupport.filter((val) => val.RecordType === this.recordtype)[0]
      )
    );
    const parsedData = JSON.parse(JSON.stringify(mapping));
    const uniqueFields = this.uniqueArticleFields(parsedData);
    const fieldsData = {};
    if (uniqueFields.includes('caseObject.Comments')) {
      const caseID = this.casedata?.Id;
      const commentsList = await getComments({ caseID });
      const comments = JSON.parse(JSON.stringify(commentsList));
      comments.sort(
        (a, b) => new Date(b.CreatedDate) - new Date(a.CreatedDate)
      );
      const caseComments = comments.flatMap((item) =>
        [item.CommentBody, item.Body, item.TextBody].filter(
          (content) => content
        )
      );
      const commentField = caseComments.map((comment) => {
        const doc = new DOMParser().parseFromString(
          comment,
          'text/html'
        );
        const filterArray = this.removeFeedContentList;
        const completeContent = doc.body.textContent || '';
        const thread = completeContent.split(
          '--------------- Original Message ---------------'
        );
        let element = thread[0];
        const allElements = element.split('\n');
        for (const x in filterArray) {
          const regexPattern = new RegExp(
            filterArray[x].replace(/\(\\w\+\)/g, '(.*?)\\')
          );
          for (const y in allElements) {
            if (regexPattern.test(allElements[y])) {
              const filteredEle = allElements[y].replace(regexPattern, '');
              allElements[y] = filteredEle;
            }
          }
          element = allElements.join('\n');
        }
        element = element.replace(/^\s+|\s+$/g, '');

        return element;
      });
      fieldsData['caseObject.Comments'] = commentField || [];
    }
    const self = this;
    uniqueFields.forEach(function (field) {
      if (field !== 'caseObject.Comments') {
        const fieldName = field.replace('caseObject.', '');
        fieldsData[field] = self.casedata[fieldName]
          ? self.casedata[fieldName]
          : '';
      }
    });
    const rawdata = {
      data: fieldsData,
      uid: this.clientSettings.uid,
      caseNumber: this.casenumber,
      selector: mapping.RecordType,
      language: 'english',
      author: this.author,
      regenerateFields: {
        titleGeneration: this.displayTitleLoader
        // summaryGeneration: this.displaySummaryLoader
      }
    };
    Object.keys(this.generateSummaryFields).forEach((field)=>{
      rawdata.regenerateFields[field]=this.generateSummaryFields[field]
    })
    return rawdata;
  }

  callRegenerationMethod() {
    this.handleRetry();
  }

  async continueRegenerationMethod() {
    await this.getCase();
    const rawdata = await this.createAutoGenerationPayload();
    const compareMetaUrl = `${this.endpoint}/kcs-anlytics/rest/anlytics/autoGeneratedTitle/compare-hashes`;
    const compareMetaresult = await fetch(compareMetaUrl, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        accept: '/',
        'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
        'ngrok-skip-browser-warning': true,
        Authorization: `Bearer ${this.jwttoken}`
      },
      body: JSON.stringify(rawdata)
    }).then((response) => response.json());
    if (compareMetaresult && compareMetaresult.data.match) {
      this.displayTitleLoader = false;
      this.displaySummaryLoader = false;
      // Object.keys(this.generateSummaryFields).forEach((field)=>{
      //   this.generateSummaryFields[field]=false;
      // })
      let tempGenerateSummary = { ...this.generateSummaryFields };
      Object.keys(tempGenerateSummary).forEach((field) => {
        tempGenerateSummary[field] = false;
      })
      this.generateSummaryFields = { ...tempGenerateSummary };
      this.template
        .querySelector(this.knowblerModalComponent)
        .showRegenerateModal('openNoRegenerationPopup');
    } else {
      this.template
        .querySelector(this.knowblerModalComponent)
        .showRegenerateModal('openWarningRegenerationPopup');
    }
  }

  async regenerateContent(e) {
    const fieldName = e.currentTarget.dataset.item;
    const autoGenConfig =
      this.kcssupport &&
      this.kcssupport.filter((val) => val.RecordType === this.recordtype)[0]
        .autoGenConfig.config;

    const generationType =
      autoGenConfig &&
      autoGenConfig.filter((val) => val.field === fieldName)[0].generateType;

    if (generationType === 'titleGeneration') {
      this.displayTitleLoader = true;
    } else {
      this.displaySummaryLoader = true;
      let tempGenerateSummary={...this.generateSummaryFields};
        Object.keys(tempGenerateSummary).forEach((field)=>{
          tempGenerateSummary[field]=true;
        })
      this.generateSummaryFields={...tempGenerateSummary};
    }
    try {
      if (this.currentid) {
        const articleNumber = await getArticleNumber({
          articleid: this.currentid
        });
        const articleMetaPayload = {
          uid: this.clientSettings.uid,
          article_id: articleNumber,
          doc_id: this.currentid
        };
        const url = `${this.endpoint}/kcs-anlytics/rest/anlytics/autoGeneratedTitle/get-article-meta`;
        const result = await fetch(url, {
          method: 'POST',
          headers: {
            'content-type': 'application/json',
            accept: '/',
            'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
            'ngrok-skip-browser-warning': true,
            Authorization: `Bearer ${this.jwttoken}`
          },
          body: JSON.stringify(articleMetaPayload)
        }).then((response) => response.json());
        const storeData = result.data;
        if (storeData && storeData.template_id !== this.recordtypeID) {
          this.displayTitleLoader = false;
          this.displaySummaryLoader = false;
          let tempGenerateSummary={...this.generateSummaryFields};
          Object.keys(tempGenerateSummary).forEach((field) => {
            tempGenerateSummary[field] = false;
          })
          this.generateSummaryFields = { ...tempGenerateSummary };
          this.template
            .querySelector(this.knowblerModalComponent)
            .showRegenerateModal('openRegenerateTemplateErrorPopup');
        } else if (
          storeData &&
          storeData.casenumber !== this.casenumber
        ) {
          this.template
            .querySelector(this.knowblerModalComponent)
            .showRegenerateModal('openDifferentCaseRegenerationPopup');
        } else {
          this.continueRegenerationMethod();
        }
      } else {
        this.continueRegenerationMethod();
      }
    } catch (error) {
      this.template
        .querySelector(this.knowblerModalComponent)
        .showError(error);
    }
    this.handleChange('setValue');
    this.populateContentHealthCheck();
    this.checkEmptyValidator = this.handleChangeCheck();
  }

  publisharticlemethods(publishmethodparameter) {
    this.publishmethod = publishmethodparameter;
    this.template.querySelector('lightning-record-edit-form').submit(this.fieldset);

  }

  @api handleRetry() {
    this.dispatchEvent(
      new CustomEvent('createarticle', {
        detail: {
          displayTitleLoader: this.displayTitleLoader,
          displaySummaryLoader: this.displaySummaryLoader,
          generateSummaryFields: this.generateSummaryFields //need to check KameshR
        }
      })
    );
  }
  addBranchIntoTree(pathArray, tree) {
    let found = 0;
    for (const val of tree) {
      if (pathArray[0] === val.name) {
        found = 1;
        pathArray = pathArray.splice(1);
        const res = this.addBranchIntoTree(pathArray, val.childCategories);
        if (res && res.length) {
          val.childCategories = res;

          return tree;
        }
        val.childCategories.push(res);

        return tree;
      }
    }
    if (!found) {
      let obj = { name: pathArray[pathArray.length - 1], childCategories: [] };
      pathArray[pathArray.length - 1] = obj;
      let z = pathArray.length - 1;
      while (z > 0) {
        obj = { name: pathArray[z - 1], childCategories: [pathArray[z]] };
        pathArray[z - 1] = obj;
        pathArray.pop();
        z -= 1;
      }

      return pathArray[0];
    }

    return tree;
  }

  findPath(node, nodeName, currentPath = []) {
    // If the current node matches the desired node name, return the current path
    if (node.name === nodeName) {
        return [...currentPath, node.name];
    }

    // If the current node has child categories, recursively search in them
    if (node.childCategories && node.childCategories.length > 0) {
        for (let child of node.childCategories) {
            let path = this.findPath(child, nodeName, [...currentPath, node.name]);
            if (path) {
                return path;
            }
        }
    }

    // If the node is not found, return null
    return null;
}

    async generateContentHealth() {
    const copyContentHealthSettings = JSON.parse(JSON.stringify(this.contentHealthSettings));
    this.template.querySelector(this.knowblerModalComponent).showContentHealthModal({state : 'showLoader'});
    const uid = JSON.parse(JSON.stringify(this.clientSettings)).uid;
    const url = `${this.endpoint}/kcs-anlytics/rest/anlytics/agent-request/generate-content-health`;
    const dataCategory = JSON.parse(this.alldatacategories);
    const selectedDataCategory = JSON.parse(JSON.stringify(this.dataCategories)).length ? JSON.parse(this.dataCategories) : [];
    let attachCategoryPath = [];
    let finalCategoryTree;
    for (const val of selectedDataCategory) {
      for (const iterator of dataCategory.categoryGroups) {
        if (iterator.topCategories && val.categoryGroup === iterator.name) {
          for (const root of iterator.topCategories) {
            root.label = "All";
            root.name = "All"
            let path = this.findPath(root, val.name);
            path.splice(1, 0, val.categoryGroup);
            attachCategoryPath.push(path);
          }
        }
      }
    }


    if(attachCategoryPath && attachCategoryPath.length) {
      attachCategoryPath.forEach(val => {
        if (finalCategoryTree) {
          const resultTree = this.addBranchIntoTree(
            val,
            finalCategoryTree
          );
          finalCategoryTree = resultTree;
        } else {
          let obj = {
            name: val[
              val.length - 1
            ],
            childCategories: []
          };
          val[
            val.length - 1
          ] = obj;
          let z = val.length - 1;
          while (z > 0) {
            obj = {
              name: val[z - 1],
              childCategories: [val[z]]
            };
            val[z - 1] = obj;
            val.pop();
            z -= 1;
          }
          finalCategoryTree = val;
        }
      })
    }

    let fields = JSON.parse(JSON.stringify(this.fieldset));
    let summaryContent = ''
    let config = JSON.parse(JSON.stringify(this.kcssupport));
    config.forEach(element => {
      if (element.RecordType === this.recordtype) {
          for(let i=0;i<this.contentHealthCheckArray.length;i++){
            if(!(this.contentHealthCheckArray[i]==='Title')){
              if(this.fieldset[this.contentHealthCheckArray[i]] && this.fieldset[this.contentHealthCheckArray[i]].length>0){
                summaryContent+=this.fieldset[this.contentHealthCheckArray[i]]+' ';
              }
            }
          }
      }
    });
    let obj = {
      categories: finalCategoryTree ? finalCategoryTree[0] : {},
      article_id: '',
      uid,
      title: fields.Title || '',
      summary: (summaryContent && summaryContent.length>0) ? summaryContent : '',
    }
    if(this.contentHealthData && this.calculateContentHealthApiPayload && this.calculateContentHealthApiPayload === JSON.stringify(obj)) {
      this.template.querySelector(this.knowblerModalComponent).showContentHealthModal({state : 'showHealthScore',data: this.contentHealthData, settings : copyContentHealthSettings});
      this.populateContentHealthCheck();
      this.checkEmptyValidator=this.handleChangeCheck();
      return;
    }
      this.calculateContentHealthApiPayload = JSON.stringify(obj);

    obj.article_id = Date.now().toString()
    const payloadObj = {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'accept': '/',
        'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
        'ngrok-skip-browser-warning':true,
        'Authorization': `Bearer ${this.jwttoken}`
      },
      body: JSON.stringify(obj),
    };
    try {
      const generatedContentHealth = await fetch(url, payloadObj).then((response) => response.json());
      if(generatedContentHealth && generatedContentHealth.data && generatedContentHealth.data.data) {
        this.contentHealthData = generatedContentHealth.data.data;
        this.template.querySelector(this.knowblerModalComponent).showContentHealthModal({state : 'showHealthScore',data: generatedContentHealth.data.data, settings : copyContentHealthSettings});
      } else {
        this.template.querySelector(this.knowblerModalComponent).showContentHealthModal({state : 'showCalculateHealthError',data: generatedContentHealth.data});
      }
    } catch (e) {
      this.template.querySelector(this.knowblerModalComponent).showError(e);
    }
    this.populateContentHealthCheck();
    this.checkEmptyValidator=this.handleChangeCheck();
  }
}